# Generated by Django 5.0.6 on 2024-06-24 22:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(max_digits=5, decimal_places=2)),
                ('lot_no', models.CharField(max_length=50, null=True)),
                ('width', models.DecimalField(max_digits=5, decimal_places=2, null=True)),
                ('net_weight', models.DecimalField(max_digits=5, decimal_places=2, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Color')),
                ('lab_no', models.CharField(max_length=50)),
                ('weight_unit', models.CharField(max_length=5, null=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Fabric')),
                ('fab_id', models.IntegerField(null=True)),
            ],
        ),
    ]
